// <auto-generated />
using ArtigoSQLite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtigoSQLite.Migrations
{
    [DbContext(typeof(EleicoesDbContext))]
    [Migration("20180928153821_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("ArtigoSQLite.Model.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<string>("Partido");

                    b.HasKey("Id");

                    b.ToTable("Candidato");

                    b.HasData(
                        new { Id = 1, Nome = "ALVARO DIAS", Numero = 19, Partido = "PODE" },
                        new { Id = 2, Nome = "CABO DACIOLO", Numero = 51, Partido = "PATRI" },
                        new { Id = 3, Nome = "CIROS GOMES", Numero = 12, Partido = "PDT" },
                        new { Id = 4, Nome = "EYMAEL", Numero = 27, Partido = "DC" },
                        new { Id = 5, Nome = "FERNANDO HADDAD", Numero = 13, Partido = "PT" },
                        new { Id = 6, Nome = "GERALDO ALCKIMIN", Numero = 45, Partido = "PSDB" },
                        new { Id = 7, Nome = "GUILHERME BOULOS", Numero = 50, Partido = "PSOL" },
                        new { Id = 8, Nome = "HENRIQUE MEIRELLES", Numero = 15, Partido = "MDB" },
                        new { Id = 9, Nome = "JAIR BOLSONARO", Numero = 17, Partido = "PSL" },
                        new { Id = 10, Nome = "JOÃO AMOÊDO", Numero = 30, Partido = "NOVO" },
                        new { Id = 11, Nome = "JOÃO GOULART FILHO", Numero = 54, Partido = "PPL" },
                        new { Id = 12, Nome = "MARINA SILVA", Numero = 18, Partido = "REDE" },
                        new { Id = 13, Nome = "VERA", Numero = 17, Partido = "PSTU" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
